using Banned.CodeDiff.Models;
using Banned.CodeDiff.Services;
using Banned.CodeDiff.Services.TextMate;
using Banned.CodeDiff.Utils;
using NUnit.Framework;

namespace Banned.CodeDiff.Tests;

/// <summary>
/// Smoke tests for the M5 syntax pipeline: HighlightAst.ProcessAst (processAST port),
/// the TextMate engine, and the DiffFile.initSyntax link. Golden parity with the
/// upstream shiki engine lives in SyntaxGoldenTests (generated by tests/js-harness).
/// </summary>
[TestFixture]
public class SyntaxHighlightTests
{
    // ---- HighlightAst.ProcessAst ----

    [Test]
    public void ProcessAst_SingleLineNodes_AppendWithRunningIndexes()
    {
        var ast = new SyntaxNode
        {
            Type     = "root",
            Children =
            [
                new SyntaxNode
                {
                    Type = "element", Properties = new SyntaxNodeProperties { Style = "--diff-view-light:#111;" },
                    Children = [new SyntaxNode { Type = "text", Value = "ab" }],
                },
                new SyntaxNode { Type = "text", Value = "cd" },
            ],
        };

        var result = HighlightAst.ProcessAst(ast);

        Assert.That(result.SyntaxFileLineNumber, Is.EqualTo(1));
        Assert.That(result.SyntaxFileObject.Keys, Is.EqualTo(new[] { 1 }));

        var line = result.SyntaxFileObject[1];
        Assert.That(line.Value, Is.EqualTo("abcd"));
        Assert.That(line.ValueLength, Is.EqualTo(4));

        Assert.That(line.NodeList![0].Node.StartIndex, Is.EqualTo(0));
        Assert.That(line.NodeList![0].Node.EndIndex, Is.EqualTo(1));
        Assert.That(line.NodeList![0].Wrapper!.Properties!.Style, Is.EqualTo("--diff-view-light:#111;"));

        Assert.That(line.NodeList![1].Node.StartIndex, Is.EqualTo(2));
        Assert.That(line.NodeList![1].Node.EndIndex, Is.EqualTo(3));
        Assert.That(line.NodeList![1].Wrapper, Is.Null);
    }

    [Test]
    public void ProcessAst_MultiLineNode_SplitsIntoPerLineChildren()
    {
        // One text node spanning three lines: "a\nbb\nccc" (no trailing newline).
        var node = new SyntaxNode { Type = "text", Value = "a\nbb\nccc" };
        var ast  = new SyntaxNode { Type = "root", Children = [node] };

        var result = HighlightAst.ProcessAst(ast);

        Assert.That(result.SyntaxFileLineNumber, Is.EqualTo(3));

        var line1 = result.SyntaxFileObject[1];
        Assert.That(line1.Value, Is.EqualTo("a\n"));
        Assert.That(line1.NodeList![0].Node.StartIndex, Is.EqualTo(0));
        Assert.That(line1.NodeList![0].Node.EndIndex, Is.EqualTo(1));

        var line2 = result.SyntaxFileObject[2];
        Assert.That(line2.Value, Is.EqualTo("bb\n"));
        Assert.That(line2.NodeList![0].Node.StartIndex, Is.EqualTo(0));
        Assert.That(line2.NodeList![0].Node.EndIndex, Is.EqualTo(2));

        var line3 = result.SyntaxFileObject[3];
        Assert.That(line3.Value, Is.EqualTo("ccc"));
        Assert.That(line3.NodeList![0].Node.StartIndex, Is.EqualTo(0));
        Assert.That(line3.NodeList![0].Node.EndIndex, Is.EqualTo(2));

        // The original node was split into per-line children.
        Assert.That(node.Children!.Select(c => c.Value), Is.EqualTo(new[] { "a\n", "bb\n", "ccc" }));
    }

    [Test]
    public void ProcessAst_EmptyLinesFromNewlineOnlyNode()
    {
        var ast = new SyntaxNode { Type = "root", Children = [new SyntaxNode { Type = "text", Value = "\n\n" }] };

        var result = HighlightAst.ProcessAst(ast);

        // JS "\n\n".split("\n") → ["", "", ""], the first two keep their newline.
        Assert.That(result.SyntaxFileLineNumber, Is.EqualTo(3));
        Assert.That(result.SyntaxFileObject[1].Value, Is.EqualTo("\n"));
        Assert.That(result.SyntaxFileObject[2].Value, Is.EqualTo("\n"));
        Assert.That(result.SyntaxFileObject[3].Value, Is.EqualTo(""));
        Assert.That(result.SyntaxFileObject[3].NodeList![0].Node.EndIndex, Is.EqualTo(-1));
    }

    // ---- TextMate engine ----

    [Test]
    public void HasRegisteredCurrentLang_MatchesIdsAndAliases()
    {
        var engine = TextMateHighlighter.Instance;

        Assert.That(engine.HasRegisteredCurrentLang("cs"), Is.True);
        Assert.That(engine.HasRegisteredCurrentLang("csharp"), Is.True);
        Assert.That(engine.HasRegisteredCurrentLang("ts"), Is.True);
        Assert.That(engine.HasRegisteredCurrentLang("vue"), Is.True, "vue grammar registered");
        Assert.That(engine.HasRegisteredCurrentLang("txt"), Is.False);
        Assert.That(engine.HasRegisteredCurrentLang("unknown-lang"), Is.False);
    }

    [Test]
    public void GetAst_CSharp_CoversEveryRawLineAndColorsKeywords()
    {
        var raw = """
            using System;

            namespace Demo
            {
                public class Calculator
                {
                    public int Add(int a, int b)
                    {
                        return a + b;
                    }
                }
            }
            """ + "\n";

        var engine = TextMateHighlighter.Instance;

        var ast = engine.GetAst(raw, "calculator.cs", "cs", "light");

        Assert.That(ast, Is.Not.Null);

        var result = engine.ProcessAst(ast!);

        var rawLines = raw.Split('\n');

        Assert.That(result.SyntaxFileLineNumber, Is.EqualTo(rawLines.Length));

        for (var i = 1; i <= rawLines.Length; i++)
        {
            // SyntaxLine values keep the trailing newline except on the last line.
            var expected = i < rawLines.Length ? rawLines[i - 1] + "\n" : rawLines[i - 1];

            Assert.That(result.SyntaxFileObject[i].Value, Is.EqualTo(expected),
                        $"syntax line {i} must equal the raw line");
        }

        // "using" is a keyword: github-light keyword color is #d73a49 (the engine
        // emits the upper-cased form, mirroring shiki's ColorMap handling).
        var usingLine = result.SyntaxFileObject[1];
        var usingSpan = usingLine.NodeList!.First(s => s.Node.Value == "using");

        Assert.That(usingSpan.Wrapper!.Properties!.Style, Does.Contain("--diff-view-light:#D73A49"));
        Assert.That(usingSpan.Wrapper.Properties.Style, Does.Contain("--diff-view-dark:#F97583"));
    }

    [Test]
    public void GetAst_BlockComment_StateCarriesAcrossLines()
    {
        var raw = "/* start\nstill comment\nend */\nint x;\n";

        var engine  = TextMateHighlighter.Instance;
        var result  = engine.ProcessAst(engine.GetAst(raw, "a.cs", "cs", "light")!);

        // Line 2 sits inside the block comment opened on line 1 — the rule stack
        // must carry over, giving it the comment color instead of plain source.
        var line2 = result.SyntaxFileObject[2];
        Assert.That(line2.Value, Is.EqualTo("still comment\n"));
        Assert.That(line2.NodeList!.Any(s => s.Wrapper?.Properties?.Style?.Contains("--diff-view-light:#6A737D") == true),
                    Is.True, "line inside a block comment should use the comment color");
    }

    [Test]
    public void GetAst_UnsupportedLang_ReturnsNull()
    {
        Assert.That(TextMateHighlighter.Instance.GetAst("hello", "a.txt", "txt", "light"), Is.Null);
        Assert.That(TextMateHighlighter.Instance.GetAst("hello", "a.unknown", "unknown", "light"), Is.Null);
    }

    [Test]
    public void GetAst_IgnoredFileName_ReturnsNull()
    {
        var engine = TextMateHighlighter.Instance;

        engine.SetIgnoreSyntaxHighlightList([new FileNameIgnorePattern("generated.cs")]);

        try
        {
            Assert.That(engine.GetAst("int x;", "generated.cs", "cs", "light"), Is.Null);
        }
        finally
        {
            engine.SetIgnoreSyntaxHighlightList([]);
        }
    }

    // ---- DiffFile.initSyntax link ----

    private const string CsOld = """
        using System;

        namespace Demo
        {
            public class Calculator
            {
                public int Add(int a, int b)
                {
                    return a + b;
                }
            }
        }
        """;

    private const string CsNew = """
        using System;

        namespace Demo
        {
            public class Calculator
            {
                public int Add(int a, int b)
                {
                    return a + b + 1;
                }
            }
        }
        """;

    private static readonly string[] CsHunks =
    [
        """
        diff --git a/calculator.cs b/calculator.cs
        --- a/calculator.cs
        +++ b/calculator.cs
        @@ -7,7 +7,7 @@ public class Calculator
                 public int Add(int a, int b)
                 {
        -            return a + b;
        +            return a + b + 1;
                 }
             }
        """,
    ];

    [Test]
    public void DiffFile_InitSyntax_FillsOldAndNewSyntaxLines()
    {
        var df = new DiffFile("calculator.cs", CsOld, "calculator.cs", CsNew, CsHunks);

        df.InitTheme("light");
        df.Init();

        Assert.That(df.HighlighterName, Is.EqualTo("textmate"));

        var oldSyntax = df.GetOldSyntaxLine(1);
        var newSyntax = df.GetNewSyntaxLine(1);

        Assert.That(oldSyntax, Is.Not.Null);
        Assert.That(oldSyntax!.Value, Is.EqualTo("using System;\n"));
        Assert.That(newSyntax, Is.Not.Null);
        Assert.That(newSyntax!.Value, Is.EqualTo("using System;\n"));

        // Both changed lines are present in the syntax tables.
        Assert.That(df.GetOldSyntaxLine(9)!.Value.Trim(), Is.EqualTo("return a + b;"));
        Assert.That(df.GetNewSyntaxLine(9)!.Value.Trim(), Is.EqualTo("return a + b + 1;"));
    }

    [Test]
    public void DiffFile_InitSyntax_LongFileSkipsHighlighting()
    {
        var big = string.Join("\n", Enumerable.Range(0, TextMateHighlighter.Instance.MaxLineToIgnoreSyntax + 5)
                                              .Select(i => $"int v{i};"));

        var df = new DiffFile("big.cs", big, "big.cs", big, ["@@ -1 +1 @@\n-old\n+new\n"]);

        df.Init();

        Assert.That(df.GetOldSyntaxLine(1), Is.Null, "files over maxLineToIgnoreSyntax stay unhighlighted");
    }

    [Test]
    public void DiffFile_InitSyntax_IsIdempotent()
    {
        var df = new DiffFile("calculator.cs", CsOld, "calculator.cs", CsNew, CsHunks);

        df.Init();
        df.InitSyntax();

        Assert.That(df.GetOldSyntaxLine(1), Is.Not.Null);
        Assert.That(df.GetNewSyntaxLine(1), Is.Not.Null);
    }

    // ---- SourceFile.DoSyntax syntax-result LRU (the getFile counterpart) ----

    [Test]
    public void DoSyntax_SameContentTwice_AdoptsMemoizedResult()
    {
        try
        {
            const string content = "using System;\n\n// a comment\nvar x = 1;\n";

            var first = new SourceFile(content, "cs", "cached.cs");
            first.DoRaw();
            first.DoSyntax();

            var second = new SourceFile(content, "cs", "cached.cs");
            second.DoRaw();
            second.DoSyntax();

            Assert.That(second.HasDoSyntax, Is.True);
            Assert.That(second.SyntaxFile, Is.SameAs(first.SyntaxFile),
                        "same inputs reuse the memoized tokenization result");
        }
        finally
        {
            SourceFile.ClearFileCache();
        }
    }

    [Test]
    public void DoSyntax_ClearedAndRebuilt_SyntaxResultsAreIdentical()
    {
        try
        {
            const string content = "using System;\nnamespace N\n{\n    /* block */\n    var s = \"txt\";\n}\n";

            var first = new SourceFile(content, "cs", "twice.cs");
            first.DoRaw();
            first.DoSyntax();

            SourceFile.ClearFileCache();

            var second = new SourceFile(content, "cs", "twice.cs");
            second.DoRaw();
            second.DoSyntax();

            Assert.That(second.SyntaxFile, Is.Not.SameAs(first.SyntaxFile));

            // Same content re-tokenized from scratch must reproduce every span field.
            Assert.That(second.SyntaxFile!.Keys, Is.EqualTo(first.SyntaxFile!.Keys));

            foreach (var (lineNumber, firstLine) in first.SyntaxFile)
            {
                var secondLine = second.SyntaxFile[lineNumber];

                Assert.That(secondLine.Value, Is.EqualTo(firstLine.Value), $"line {lineNumber} value");

                var firstSpans  = firstLine.NodeList!;
                var secondSpans = secondLine.NodeList!;

                Assert.That(secondSpans.Count, Is.EqualTo(firstSpans.Count), $"line {lineNumber} span count");

                for (var i = 0; i < firstSpans.Count; i++)
                {
                    Assert.That(secondSpans[i].Node.Value, Is.EqualTo(firstSpans[i].Node.Value),
                                $"line {lineNumber} span {i} value");
                    Assert.That(secondSpans[i].Wrapper?.Properties?.Style,
                                Is.EqualTo(firstSpans[i].Wrapper?.Properties?.Style),
                                $"line {lineNumber} span {i} style");
                }
            }
        }
        finally
        {
            SourceFile.ClearFileCache();
        }
    }

    [Test]
    public void DoSyntax_ClassAst_AnyThemeHitsTheMemoizedResult()
    {
        try
        {
            const string content = "var themed = true;\n";

            var light = new SourceFile(content, "cs", "themed.cs");
            light.DoRaw();
            light.DoSyntax(theme: "light");

            var dark = new SourceFile(content, "cs", "themed.cs");
            dark.DoRaw();
            dark.DoSyntax(theme: "dark");

            Assert.That(dark.SyntaxFile, Is.SameAs(light.SyntaxFile),
                        "class ASTs carry both theme colors — a theme flip reuses the memoized result");
        }
        finally
        {
            SourceFile.ClearFileCache();
        }
    }

    [Test]
    public void DoSyntax_EngineConfigChange_DropsMemoizedResults()
    {
        try
        {
            const string content = "var cfg = 1;\n";

            var first = new SourceFile(content, "cs", "cfg.cs");
            first.DoRaw();
            first.DoSyntax();

            TextMateHighlighter.Instance.SetIgnoreSyntaxHighlightList([]);

            var second = new SourceFile(content, "cs", "cfg.cs");
            second.DoRaw();
            second.DoSyntax();

            Assert.That(second.SyntaxFile, Is.Not.SameAs(first.SyntaxFile),
                        "config changes must re-tokenize");
        }
        finally
        {
            SourceFile.ClearFileCache();
        }
    }
}
